//
// Created by yk029484 on 12/14/2023.
//

#ifndef GRAPH_PUZZLE_GAME_SQV51_GRAPHPUZZLEGAME_H
#define GRAPH_PUZZLE_GAME_SQV51_GRAPHPUZZLEGAME_H
#include "iostream"


class GraphPuzzleGame {

};


#endif //GRAPH_PUZZLE_GAME_SQV51_GRAPHPUZZLEGAME_H
